spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 32MB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 5000

jwt:
  secret: ${JWT_SECRET:MY_SUPER_SECRET_KEY}

yandex:
  storage:
    bucket: ${YANDEX_STORAGE_BUCKET:dummy-bucket}
    access-key: ${YANDEX_STORAGE_KEY:dummy-access-key}
    secret-key: ${YANDEX_STORAGE_SECRET:dummy-secret-key}
    endpoint: ${YANDEX_STORAGE_ENDPOINT:https://storage.yandexcloud.net}
    public-base-url: ${YANDEX_STORAGE_PUBLIC_BASE_URL:${YANDEX_STORAGE_ENDPOINT:https://storage.yandexcloud.net}}
