spring:
  profiles:
    active: dev


lifepay:
  base-url: https://api-ecom.life-pay.ru/v1
  service-id: 123456
  api-key: lifepay_api_key_here
  notification-url: https://<my-domain>/payment/3ds_return
